Create parser-mprr
dadosjusbr/parser-mprr pull request #1
Opened 2022-06-05 14:43 UTC by duardoqueiroz

2022-06-05 15:51 UTC, danielfireman requested changes

2022-06-05 15:51 UTC, danielfireman commented on src/data.py
> +                f"{self.output_folder}/membros-ativos-contracheque-{self.month}-{self.year}.xlsx"
O coletor está retornando os nomes nesse formato?

2022-06-05 15:51 UTC, danielfireman commented on src/main.py
> +    leaf = parse(data, coleta.chave_coleta, MONTH, YEAR)
Tem certeza que quer repetir o nome da variável leaf? Me parece um problema.

2022-06-05 15:51 UTC, danielfireman commented on src/main.py
> +    leaf = Coleta.FolhaDePagamento()
o que significa leaf? Talvez escolher um nome de variável mais claro?

2022-06-05 15:51 UTC, danielfireman commented on src/metadata.py
> +    metadata = Coleta.Metadados()
Você conferiu cada um desses campos? Lembrando que cada coletor/parser é diferente e não devemos apenas copiar e colar os metadados.

2022-06-05 15:51 UTC, danielfireman commented on src/main.py
> +  datas = data.load(file_names,YEAR,MONTH,OUTPUT_FOLDER)
Pode usar `data`. O plural em de `data` é `datum`, mas é bem pouco usado nesses casos.

2022-06-05 15:51 UTC, danielfireman commented on src/main.py
> +  datas = data.load(file_names,YEAR,MONTH,OUTPUT_FOLDER)
Esse código está formatado (acredito que não pois não há espaço depois da vírgula)? Se não, você deve realizar uma formatação automática.

2022-06-06 12:50 UTC, duardoqueiroz commented on src/data.py
> +                f"{self.output_folder}/membros-ativos-contracheque-{self.month}-{self.year}.xlsx"
sim

2022-06-06 12:56 UTC, duardoqueiroz commented on src/main.py
> +    leaf = parse(data, coleta.chave_coleta, MONTH, YEAR)
Nos outros parsers também está dessa forma

2022-06-06 13:37 UTC, duardoqueiroz commented on src/metadata.py
> +    metadata = Coleta.Metadados()
Sim

2022-06-06 23:57 UTC, danielfireman approved these changes
Muito bacana!

2022-06-07 12:43 UTC, merged